"use client";

import { CheckCircle2, Eye, EyeOff, LoaderCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useEffect, useState } from "react";

type Invite = { email: string; role: string; expiresAt: string };

export function AcceptInviteForm({ token }: { token: string }) {
  const [invite, setInvite] = useState<Invite | null>(null);
  const [error, setError] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  useEffect(() => { void (async () => { const response = await fetch(`/api/invitations/${token}`); const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Unable to verify invitation."); else setInvite(payload.data); })(); }, [token]);
  async function submit(formData: FormData) { setError(""); const response = await fetch("/api/invitations/accept", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, name: formData.get("name"), password: formData.get("password") }) }); const payload = await response.json(); if (!response.ok) return setError(payload.error ?? "Unable to accept invitation."); await signIn("credentials", { email: payload.data.email, password: formData.get("password"), callbackUrl: "/admin/dashboard" }); }
  return <main className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><section className="w-full max-w-md rounded-xl border bg-white p-7 shadow-sm"><Link href="/" className="text-sm font-semibold text-slate-950">Transit Ops</Link>{!invite && !error && <div className="flex min-h-80 items-center justify-center"><LoaderCircle className="animate-spin text-slate-400" size={26} /></div>}{error && <div className="py-12 text-center"><ShieldCheck className="mx-auto text-red-500" size={36} /><h1 className="mt-4 text-xl font-semibold text-slate-950">Invitation unavailable</h1><p className="mt-2 text-sm leading-6 text-slate-500">{error}</p><Link href="/login" className="mt-6 inline-flex rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white">Go to sign in</Link></div>}{invite && <><div className="mt-8 flex h-10 w-10 items-center justify-center rounded-full bg-emerald-50 text-emerald-700"><CheckCircle2 size={22} /></div><h1 className="mt-4 text-2xl font-semibold tracking-tight text-slate-950">You&apos;re invited</h1><p className="mt-2 text-sm leading-6 text-slate-500">Complete your account setup to join Transit Ops as a <span className="font-medium text-slate-700">{invite.role.replaceAll("_", " ").toLowerCase()}</span>.</p><form action={submit} className="mt-7 space-y-5"><label className="block text-sm font-medium text-slate-700">Invited email<input value={invite.email} disabled className="mt-2 flex h-10 w-full rounded-md border border-slate-200 bg-slate-50 px-3 text-sm text-slate-500" /></label><label className="block text-sm font-medium text-slate-700">Full name<input name="name" required autoComplete="name" placeholder="Your name" className="mt-2 flex h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10" /></label><label className="block text-sm font-medium text-slate-700">Create password<div className="relative mt-2"><input name="password" type={showPassword ? "text" : "password"} minLength={8} required autoComplete="new-password" placeholder="At least 8 characters" className="flex h-10 w-full rounded-md border border-slate-200 bg-white px-3 pr-10 text-sm outline-none focus:border-slate-900 focus:ring-2 focus:ring-slate-900/10" /><button type="button" aria-label="Show password" onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-2 text-slate-500">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label>{error && <p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="inline-flex h-10 w-full items-center justify-center rounded-md bg-slate-900 px-4 text-sm font-medium text-white hover:bg-slate-800">Create account</button></form><p className="mt-6 text-center text-sm text-slate-500">Already a member? <Link href="/login" className="font-medium text-slate-900 underline">Sign in</Link></p></>}</section></main>;
}
