"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Snapshot = { metrics: { activeVehicles: number; availableVehicles: number; inMaintenance: number; activeTrips: number; driversOnDuty: number }; vehicles: { id: string; regNumber: string; name: string; status: string }[]; trips: { id: string; source: string; destination: string; status: string; vehicle: { regNumber: string }; driver: { name: string } }[]; alerts: { id: string; vehicle: string; issue: string; status: string }[]; };
const metricLabels: [keyof Snapshot["metrics"], string][] = [["activeVehicles", "Active vehicles"], ["availableVehicles", "Available"], ["inMaintenance", "In maintenance"], ["activeTrips", "Active trips"], ["driversOnDuty", "Drivers on duty"]];

export default function DashboardPage() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const [message, setMessage] = useState("Loading live operations data…");
  const [showForm, setShowForm] = useState(false);
  const [vehicleMessage, setVehicleMessage] = useState("");
  async function loadSnapshot() { setMessage("Refreshing live operations data…"); try { const response = await fetch("/api/operations", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setSnapshot(payload.data); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load operations data."); } }
  useEffect(() => { void loadSnapshot(); }, []);
  async function createVehicle(formData: FormData) { setVehicleMessage(""); const response = await fetch("/api/vehicles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData)) }); const payload = await response.json(); if (!response.ok) return setVehicleMessage(payload.error ?? "Unable to create vehicle."); setShowForm(false); setVehicleMessage("Vehicle created."); await loadSnapshot(); }
  async function deleteVehicle(id: string) { if (!window.confirm("Remove this vehicle?")) return; const response = await fetch(`/api/vehicles/${id}`, { method: "DELETE" }); if (!response.ok) { const payload = await response.json(); setVehicleMessage(payload.error ?? "Unable to remove vehicle."); return; } await loadSnapshot(); }
  return <main className="live-dashboard"><header className="live-topbar"><Link href="/" className="landing-brand"><span>◈</span> Transit Ops</Link><nav><Link href="/">Home</Link><button onClick={() => void loadSnapshot()}>Refresh</button></nav></header><section className="live-heading"><div><p>LIVE OPERATIONS</p><h1>Command center</h1><span>{message || "Connected to the Transit Ops database"}</span></div><div className="dashboard-actions"><Link className="manage-button muted-button" href="/admin/invitations">Invite member</Link><button className="manage-button" onClick={() => setShowForm((value) => !value)}>Add vehicle +</button></div></section>{showForm && <form className="vehicle-form" action={createVehicle}><label>Registration<input name="regNumber" placeholder="BUS-204" required /></label><label>Name<input name="name" placeholder="Electric bus" required /></label><label>Type<input name="type" placeholder="Bus" required /></label><label>Capacity<input name="maxLoadCapacity" type="number" min="1" required /></label><button>Add to fleet</button></form>}{vehicleMessage && <p className="dashboard-message">{vehicleMessage}</p>}{snapshot && <><section className="live-metrics">{metricLabels.map(([key, label]) => <article key={key}><span>{label}</span><strong>{snapshot.metrics[key]}</strong><small>{key === "inMaintenance" ? "Open service exceptions" : "Updated in real time"}</small></article>)}</section><section className="live-grid"><article className="data-card"><h2>Recent trips</h2>{snapshot.trips.length ? <div className="data-list">{snapshot.trips.map((trip) => <div key={trip.id}><span><b>{trip.source} → {trip.destination}</b><small>{trip.vehicle.regNumber} · {trip.driver.name}</small></span><em>{trip.status.replaceAll("_", " ")}</em></div>)}</div> : <Empty label="No trips have been dispatched yet." />}</article><article className="data-card"><h2>Maintenance alerts</h2>{snapshot.alerts.length ? <div className="data-list">{snapshot.alerts.map((alert) => <div key={alert.id}><span><b>{alert.issue}</b><small>{alert.vehicle}</small></span><em className="alert-status">{alert.status}</em></div>)}</div> : <Empty label="No open maintenance alerts." />}</article></section><section className="data-card vehicle-data"><h2>Fleet</h2>{snapshot.vehicles.length ? <div className="fleet-table"><div className="table-head"><span>Vehicle</span><span>Type</span><span>Status</span><span /></div>{snapshot.vehicles.map((vehicle) => <div key={vehicle.id}><span><b>{vehicle.regNumber}</b></span><span>{vehicle.name}</span><em>{vehicle.status.replaceAll("_", " ")}</em><button className="delete-vehicle" onClick={() => void deleteVehicle(vehicle.id)}>Remove</button></div>)}</div> : <Empty label="Your fleet is ready for its first vehicle. Add one using the form above." />}</section></>}</main>;
}
function Empty({ label }: { label: string }) { return <p className="empty-state">{label}</p>; }
